spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/**
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (spring boot 2.5~) Hibernate ??? ?? data.sql ??
    open-in-view: false

clova:
  api-url:  https://clovastudio.stream.ntruss.com/testapp/v1/chat-completions/HCX-DASH-001
  secret-key: secret-key
  gateway-key: gateway-key